### ISSUE TITLE
heroku_san uses wrong heroku account only when pushing git 

### ISSUE THREAD

**Issue by justin808** [jqr/heroku_san#165]
Possibly related to: https://github.com/fastestforward/heroku_san/pull/86.

I can run this command with problem:

```
 git push heroku-staging develop:master
```

But if I try to run 

```
rake staging deploy
```

I get this error below.

So I run the manual command to deploy above. And then I run

```
rake staging migrate
```

```
git update-ref refs/heroku_san/deploy HEAD^{commit}
git push git@heroku.com:staging-someapp.git  refs/heroku_san/deploy:refs/heads/master

 !  Your account blah@blah.com does not have access to staging-someapp.
 !
 !  SSH Key Fingerprint: blah blah

fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
git update-ref -d refs/heroku_san/deploy
rake aborted!
Command failed with status (128): [git push git@heroku.com:staging-someapp....]
/Users/justin/.rvm/gems/ruby-2.0.0-p451@someapp/gems/heroku_san-4.3.2/lib/heroku_san/git.rb:23:in `git_push'
```

**Comment by justin808** [comment]
@kmayer @Jaco-Pretorius Any updates on this issue? I'd like to recommend this gem to a few projects.

**Comment by hiattp** [comment]
I've been using this with multiple accounts for a while, it seems to work fine except an auth error-out after the migration (which doesn't seem to have any negative consequence besides being annoying). You just need to make sure the `heroku.yml` file has the correct remote:

```
production:                                                                      
  app: myapp                                                                
  repo: git@heroku.client:myapp.git                                     
staging:                                                                         
   app: myapp-staging                                                        
   repo: git@heroku.client:myapp-staging.git
```
