### ISSUE TITLE
Comments in generated example have error

### ISSUE THREAD

**Issue by justin808** [jqr/heroku_san#166]
Default config file should not have dash in comments after `config:`, as that implies a list, whereas the value should be a hash. I can submit a PR if that helps, but maybe too minor. Any way, I had deleted the examples, and then when I followed the comments, I got an error, so this is worth fixing. Also worth adding the bit about heroku_accounts and the repo option to the README.md.

``` yaml
#
# Format:
#
# <stage name>:
#   app: <Heroku app name>
#   stack: <Heroku stack, optional>
#   tag: <git tag pattern, optional>
#   repo: <git repository, optional>
#   config:
#     - <Heroku config:var name>: <Heroku config:var value>
#

production:
  app: awesomeapp
  stack: bamboo-ree-1.8.7
  tag: production/*
  config:
    BUNDLE_WITHOUT: "development:test"
    GOOGLE_ANALYTICS: "UA-12345678-1"

staging:
  stack: cedar
  app: awesomeapp-staging
  config: &default
    BUNDLE_WITHOUT: "development:test"
  addons:
    - pgbackups:auto-week
    - memcache:5mb
    - logging:basic
    - scheduler:standard

demo:
  app: awesomeapp-demo
  config: *default
```
