### ISSUE TITLE
heroku:config error

### ISSUE THREAD

**Issue by atipugin** [jqr/heroku_san#90]
Running **rake production heroku:config** causes this error:

``` shell
rake aborted!
undefined method `y' for main:Object

Tasks: TOP => heroku:config
(See full trace by running task with --trace)
```

My heroku.yml looks like this:

``` yaml
production: &defaults
  app: myappname
  stack: cedar
  config:
    BUNDLE_WITHOUT: development:test
    POSTMARK_API_KEY: mypostmarkapikey
```

**heroku_san** version is 3.0.1. Is there any solution for this?
